# Generated by Django 4.0.6 on 2023-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
