# Generated by Django 4.0.6 on 2023-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0003_alter_chat_chat_id_alter_chat_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follow_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
