# Generated by Django 4.0.6 on 2023-05-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0004_alter_block_block_id_alter_follow_follow_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='avatar',
        ),
    ]
