# Generated by Django 4.0.6 on 2023-05-07 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0005_rename_image_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='follow',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
