# Generated by Django 4.0.6 on 2023-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0012_alter_article_picture_alter_article_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.FileField(default='uploads/picture/default.jpg', upload_to='uploads/picture/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(default='uploads/video/default.mp4', upload_to='uploads/video/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='uploads/avatar/default.jpg', upload_to='uploads/avatar/%Y/%m/%d'),
        ),
    ]
