# Generated by Django 4.0.6 on 2023-05-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0014_alter_article_picture_alter_article_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.FileField(default='D:\\大学\\大三下\\移动应用软件开发\\xiao-tsing-shu\\backend\\media\\picture\\default.jpg', upload_to='D:\\大学\\大三下\\移动应用软件开发\\xiao-tsing-shu\\backend\\media\\picture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(default='D:\\大学\\大三下\\移动应用软件开发\\xiao-tsing-shu\\backend\\media\\video\\default.mp4', upload_to='D:\\大学\\大三下\\移动应用软件开发\\xiao-tsing-shu\\backend\\media\\video'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='D:\\大学\\大三下\\移动应用软件开发\\xiao-tsing-shu\\backend\\media\\avatar\\default.jpg', upload_to='D:\\大学\\大三下\\移动应用软件开发\\xiao-tsing-shu\\backend\\media\\avatar'),
        ),
    ]
