# Generated by Django 4.0.6 on 2023-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0016_alter_article_picture_alter_article_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hot',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.FileField(upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(upload_to='video'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='avatar'),
        ),
    ]
