# Generated by Django 4.0.6 on 2023-05-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0017_article_hot_alter_article_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.FileField(default='', upload_to='article_cover'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.FileField(default='', upload_to='article_media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='user_avatar'),
        ),
    ]
