# Generated by Django 4.0.6 on 2023-05-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0018_remove_article_picture_remove_article_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='article_media')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='media',
            field=models.JSONField(default=list),
        ),
    ]
