# Generated by Django 4.0.6 on 2023-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiao_tsing_shu', '0019_media_alter_article_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(upload_to='article_cover/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(upload_to='article_media/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='user_avatar/%Y%m%d'),
        ),
    ]
